# Generated by Django 3.2.5 on 2021-12-28 21:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(default='', max_length=900)),
                ('image', models.ImageField(upload_to='')),
                ('linkedinId', models.CharField(max_length=100)),
                ('twitter', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Opportunity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('lastdate', models.DateField()),
                ('description', models.CharField(default='', max_length=900)),
                ('image', models.ImageField(upload_to='')),
                ('applylink', models.CharField(max_length=500)),
                ('category', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='EmpowerHerApp.category')),
            ],
        ),
    ]
