# Generated by Django 3.2.5 on 2021-12-28 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EmpowerHerApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='opportunity',
            name='isForWomen',
            field=models.BooleanField(default=False),
        ),
    ]
